### ISSUE TITLE
能不能提个建议？

### ISSUE THREAD

**Issue by fxqy** [Akegarasu/aki-cron#1]
不错啊，我都已经用起来了👍👍👍❤❤❤，现在用"write *.rtf"文件来做工作提醒。结合msys2的shell工具还能做自动上传任务，很完美啊。
```
# 测试一下
0 15 18 * * ? write.exe d:\software\aki-cron\tasks\ta.rtf
0 16 22 * * ? write.exe d:\software\aki-cron\tasks\tb.rtf
// 1 * * * * ? notepad
# 先设置环境变量C:\msys64\usr\bin
2 1 17 * * ? bash d:\software\aki-cron\tasks\sha.sh

```
冒昧的提个建议啊，就是能不能做个信息框，用来提示信息的，现在我是用write *.rtf来做提醒，感觉有点麻烦啊

**Comment by Akegarasu** [comment]
这个项目本质上是用来在windows上实现linux里的crontab的，因此crontab没有的功能大概不会添加进来
但是这个功能并不需要在本项目中实现也可以：你可以尝试在批处理文件中调用vb来生成一个windows的提示框，如下所示
```sh
mshta vbscript:msgbox("content",64,"title")(window.close)
```
![image](https://user-images.githubusercontent.com/36563862/155280961-adf4241e-1f93-4ea3-b7ca-74fc5c93091a.png)

**Comment by fxqy** [comment]
> 

### 我在自己电脑上试了这个命令，但是老是报脚本错误的警告框，运行不了，没办法自己弄了个提示框

**空白msgbox和能播放音乐的msgbox：**  [msgbox.zip](https://github.com/Akegarasu/aki-cron/files/8132171/msgbox.zip)


![323804](https://user-images.githubusercontent.com/42601163/155302800-919c2cea-d9d3-4ae1-8287-8b0abb62c46f.jpg)

**Comment by fxqy** [comment]
有个问题，我在HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run下建立启动项，开机后用如下的vbs在后台启动(不用vbs，直接前台启动一个cmd也不执行任务)，进程在但任务不执行，log文件都不会创建。这个问题不知道是什么引起的，怀疑是不是go需要的环境在系统刚启动的时候没准备好。

```
Set wsc = Wscript.createobject("WScript.shell")
a = wsc.run ("D:\software\aki-cron\aki-cron.exe -c D:\software\aki-cron\aki-cron.txt",0)

```

**Comment by Akegarasu** [comment]
我这里复现失败 使用你提供的这个vbs使用正常

**Comment by fxqy** [comment]
> 我这里复现失败 使用你提供的这个vbs使用正常

可能是我操作系统的问题，我的win10比较老16299创意者更新，没办法又在网上找了个nnCron LITE使用正常（ 
 http://www.nncron.ru/  ）

对了你是怎么编译的，我从github拉下你的代码进入目录执行"go build ."生成exe
我的go version go1.17.7 windows/amd64
手动命令行执行或者手动运行vbs都能执行任务
重启后有进程,说明代码应该没报错啊，但不能执行任务和创建log文件，真的奇怪的问题，很郁闷😭😭😭
我还测试去除log相关代码，再重启后还是一样，不是log文件创建的问题

**Comment by Akegarasu** [comment]
尝试这个commit，并且把cron任务里所有的相对路径改为绝对路径
[4464b04](https://github.com/Akegarasu/aki-cron/commit/4464b040b1070e228e3f664180373f89aacd4b70)

**Comment by fxqy** [comment]
> 尝试这个commit，并且把cron任务里所有的相对路径改为绝对路径 [4464b04](https://github.com/Akegarasu/aki-cron/commit/4464b040b1070e228e3f664180373f89aacd4b70)

还是不行
![20220228110438043](https://user-images.githubusercontent.com/42601163/155917406-020da0c4-8a98-4a33-98b0-1971074580da.jpg)

**Comment by Akegarasu** [comment]
cron文件不用绝对路径，是相对cron.exe的路径

**Comment by fxqy** [comment]
> cron文件不用绝对路径，是相对cron.exe的路径

重启后还是不行，应该不是代码的问题，操作系统的问题，应用层解决不了
我还把代码中的log写入去掉，怕的是文件写入被阻止代码不能执行，又把配置文件改成只读读取，改了又该，还是不行
```
package main

import (
	"flag"
	"github.com/robfig/cron/v3"
	"os"
	"os/exec"
	"bufio"
	"strings"
	"regexp"
)

var (
	cronConfig string
)

func main() {

	flag.StringVar(&cronConfig, "c", "cron", "cron config file")
	flag.Parse()
	
	start_cron()

}

func start_cron(){

	file, err := os.OpenFile(cronConfig, os.O_RDONLY, os.ModePerm)
	defer file.Close()
	if err != nil {
		return;
	}

	c_parser := cron.NewParser(cron.Second | cron.Minute | cron.Hour | cron.Dom | cron.Month | cron.Dow)
	c_cron := cron.New(cron.WithSeconds())
	
	regx:=regexp.MustCompile(`\s*([*\d,-/]+)\s+([*\d,-/]+)\s+([*\d,-/]+)\s+([*\d,-/?]+)\s+([*\d,-/]+)\s+([*\d,-/?]+)\s+([a-zA-Z_-]+)\s*(.*)`)
	
	bfr := bufio.NewReader(file)
	data,_,err:= bfr.ReadLine()
	for err==nil && data!=nil {
		result:=regx.FindStringSubmatch(string(data))
		if result!=nil {
			c_str := strings.Join(result[1:7]," ")
			_, err := c_parser.Parse(c_str)
			if err != nil {
				continue;
			}
			c_cron.AddFunc(c_str, func() {
				ca:=[]string{}
				if len(result)==9 {
					ca = strings.Split(result[8], " ")
				}
				cmd := exec.Command(result[7], ca...)
				cmd.Run()
			})
			
		}
		
		data,_,err = bfr.ReadLine()
	}

	c_cron.Start()
	select {}

}

```

**Comment by fxqy** [comment]
还试了``` go build -ldflags "-H=windowsgui" . ``` 编译，虽然不用vbs就能后台运行，但也是一样的效果
